module.exports = {
  authService: require('./auth.service'),
  cityService: require('./city.service'),
  emailService: require('./email.service'),
  notificationService: require('./notification.service'),
  offerService: require('./offer.service'),
  portfolioService: require('./portfolio.service'),
  presenceService: require('./presence.service'),
  responseMetricsService: require('./responseMetrics.service'),
  serviceRequestService: require('./serviceRequest.service'),
  serviceService: require('./service.service'),
  tokenService: require('./token.service'),
  uploadService: require('./upload.service'),
  userService: require('./user.service'),
};